### ISSUE TITLE
Frame interpolation instead of plane interpolation question 

### ISSUE THREAD

**Issue by peekxc** [ggobi/tourr#110]
First I wanted to thank you for the package, I really like it. 

My question is about whether geodesic frame interpolation is available along the Stiefel manifold. In the paper: 

> COOK, ANDREAS BUJA1 DIANNE, DANIEL ASIMOV, and CATHERINE HURLEY. "Theory and computational methods for dynamic projections in high-dimensional data visualization." Journal of computational and graphical statistics (1997).

A variety of algorithms are given for interpolating either frames or planes in ways that e.g. minimizes or maximizes "whip spin" and other quantities related to the derivatives of frame/plane motion, etc. Looking at the code in `geodesic_info`, `tourr` seems to implement the zero whip-spin interpolation between planes outlined in section 12 of the paper. I was wondering if `tourr` implemented somewhere in the package one of the frame-interpolation strategies, e.g. like the one give in 13.2 that uses Givens rotations?

**Comment by dicook** [comment]
Hi Matt,

It’s not in the current package.

However, two years ago, Ursula Laa and I were working on it with a summer high school student. We got busy and didn’t pick it up again, to integrate with the package, after that summer. I think it’s pretty close to working. 

I will try to get what we have working again, and built in to tourr. 

It’s really good to get some encouragement on this topic, which inspires us to work on it. 

> On 3 Aug 2021, at 12:43 am, Matt Piekenbrock ***@***.***> wrote:
> 
> 
> First I wanted to thank you for the package, I really like it.
> 
> My question is about whether geodesic frame interpolation is available along the Stiefel manifold. In the paper:
> 
> COOK, ANDREAS BUJA1 DIANNE, DANIEL ASIMOV, and CATHERINE HURLEY. "Theory and computational methods for dynamic projections in high-dimensional data visualization." Journal of computational and graphical statistics (1997).
> 
> A variety of algorithms are given for interpolating either frames or planes in ways that e.g. minimizes or maximizes "whip spin" and other quantities related to the derivatives of frame/plane motion, etc. Looking at the code in geodesic_info, tourr seems to implement the zero whip-spin interpolation between planes outlined in section 12 of the paper. I was wondering if tourr implemented somewhere in the package one of the frame-interpolation strategies, e.g. like the one give in 13.2 that uses givens rotations?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by dicook** [comment]
Hi @peekxc Finally, getting close. Take a look at the woylier package at https://numbats.github.io/woylier/. We are in the process of getting it on CRAN, and finishing a paper for the R Journal.

**Comment by peekxc** [comment]
Very cool! :)

**Comment by dicook** [comment]
Frame interpolation is now available in the woylier package, with a paper explaining it hopefully appearing soon. Closing this issue.
