### ISSUE TITLE
Python equivalent of tourr?

### ISSUE THREAD

**Issue by IlievskiV** [ggobi/tourr#116]
Hi,

is there any good Python equivalent of this R package? I was able to find a few `tourpy` packages but they seemed to be not active:

- https://github.com/wngu6/tourpy
- https://github.com/cbalazs/tourpy

Many thanks!

**Comment by dicook** [comment]
You could look at https://logarithmic.net/langevitour/ which is a javascript implementation

> On 18 Jan 2023, at 10:08 am, Vladimir ***@***.***> wrote:
> 
> 
> Hi,
> 
> is there any good Python equivalent of this R package? I was able to find a few tourpy packages but they seemed to be not active:
> 
> 	• https://github.com/wngu6/tourpy
> 	• https://github.com/cbalazs/tourpy
> Many thanks!
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by dicook** [comment]
Take a look at https://www.youtube.com/watch?v=nYdpSXOMqN8
