### ISSUE TITLE
Global variables and reliance on global state

### ISSUE THREAD

**Issue by sa-lee** [ggobi/tourr#66]
When running `animate`, the `verbose` and `record` objects get returned to the current R session even if the verbose argument is set to FALSE.  This could cause user data  (if they have an object called `record` in their global environment) to be overwritten by the `tourr` package which might  be unexpected. 

Moreover, the reliance on global state means that functions in the current version of `tourr` now don't work outside the context of `animate`. For example in #57, the `render` functions don't work because `new_geodesic_path` can't find a verbose object. 

For the record keeping object it should only get initialised if `verbose = TRUE`.   
The simplest solution to fix this would be add a verbose argument to all the functions where you wanted to do record keeping, like the `search_*` family of functions and the `new_geoedesic_path` function. 

cc @huizezhang-sherry @uschiLaa

**Comment by sa-lee** [comment]
You can set global options with `options()` and retrieve them with `getOption()` so for example, you could set:

```{r}
# replace any time verbose is relied on to
getOption("tourr.verbose", default = FALSE)

# when tourr is loaded run if you want to start recording at the console
options(tourr.verbose= TRUE)

# in an external package use a function like this to permanently set tourr.verbose = TRUE
recorder_on <- function() {
  old <- options(tourr.verbose = TRUE)
  on.exit(opitions(old), add = TRUE)
  invisible()
}

# alternative to above is to use withr::local_options
```

**Comment by huizezhang-sherry** [comment]
This has been fixed in PR #70. To allow the record-keeping, set `options("tourr.verbose" = TRUE) `

**Comment by sa-lee** [comment]
I think you want to document this as well and also write some docs on what the record object is.

**Comment by sa-lee** [comment]
One issue I'm having is the reliance of using the record object for both record keeping but also being passed to the optimisation procedures. 

I think we also need to make sure it is fully  transparent to the end user how the record keeping is done, at this point there's a lot of duplication in the code that I think could be fixed.

**Comment by huizezhang-sherry** [comment]
The record object going everywhere is because 

1) there are some other places need it to initialise the record object, 
2) `search_*` functions need it to record search results, and 
3) `new_tour()` needs it to record the interpolation

But yea we can put some explanations in the vignette for this part of the work.
