### ISSUE TITLE
update Suggests

### ISSUE THREAD

**Issue by sa-lee** [ggobi/tourr#81]
`reshape2` is only used in the Andrew's path example - could it be removed? We also need to add extra packages for the new vignettes, like tsibble...

**Comment by uschiLaa** [comment]
Yes, actually the edges vignette code needs to be cleaned up a bit as well! I might check to see if I find an example that needs less suggested packages.

**Comment by dicook** [comment]
yes, would be good to remove the depdendency on reshape2

**Comment by dicook** [comment]
done with the reshape2 dependency, i think

**Comment by dicook** [comment]
@uschiLaa the tour.Rmd vignette doesn't show the guided tour plots like I expected. For some reason these barf in the knit, although the code works alone. It seems for all the other code, the first projection is grabbed and plotted. But for the guided tour, it doesn't seem to extract the first view.

**Comment by uschiLaa** [comment]
Yes, it throws an error related to setting "index" and that is why we don't see anything here. I think @sa-lee was going to look into that.

**Comment by sa-lee** [comment]
It looks like another globals issue (?) not sure how to fix yet cc @huizezhang-sherry

**Comment by huizezhang-sherry** [comment]
There a way to remove the global variables on index, I can implement that

**Comment by sa-lee** [comment]
So rerunning vignette locally and on actions - everything seems to work now?

**Comment by dicook** [comment]
Oh, funny: build_vignettes() still barfs, but using knit works to make the tour.Rmd vignette, BUT this doesn't save to the doc folder.

**Comment by dicook** [comment]
So I don't think it works still. I keep getting an error message when I push to github that all builds fail.

**Comment by sa-lee** [comment]
have you merged my latest PR? it should fix all of those things

**Comment by dicook** [comment]
Oh, that has definitely helped!

**Comment by sa-lee** [comment]
Great, we can close this issue now. Everything is passing on macOS and ubuntu now (with a false negative on windows).
