### ISSUE TITLE
pkgdown

### ISSUE THREAD

**Issue by dicook** [ggobi/tourr#85]
Should we follow these guidelines and shift the pkgdown files to a pkgdown directory?

"You can also put it in pkgdown/_pkgdown.yml if you want to keep the package root clutter free, or in inst/_pkgdown.yml if you want to make it available when your package is installed"

**Comment by sa-lee** [comment]
That sounds good to me. You can also trigger the deployment on github actions with `usethis::use_github_action("pkgdown")` and then delete the docs folder on the master branch.  I think you'll have to change the settings of the repo so the site is displayed from the gh-pages branch however.

**Comment by dicook** [comment]
you mean that I need to add a line to the github actions?

i don't even see a gh-pages branch

**Comment by sa-lee** [comment]
Run `usethis::use_github_action("pkgdown")` locally in the tourr project, which will create a new file in the `.github` folder to build the website. It should take care of everything else I think.

In the settings tab of this repo you need to then change where the site is deployed from, here's an example from my work:
![Screen Shot 2020-11-20 at 4 23 03 pm](https://user-images.githubusercontent.com/8033857/99762509-c8204900-2b4c-11eb-8381-db144d1386b9.png)

**Comment by dicook** [comment]
Ok, broke the web site build now, but the pkgdown directory is there and the github actions. do we need to create a gh-pages branch now?

**Comment by dicook** [comment]
Ah, it should be ok now
